language:
  java

jdk:
  - oraclejdk8
  - oraclejdk7
  
git:
  depth: 4
  
install:
  - cd ../..
  - pwd
  - git clone https://github.com/codacy/codacy-coverage-reporter.git
  - cd codacy-coverage-reporter
  - sbt assembly
  - cd ../Walkersneps/SnepsUtils
  - ls ../../codacy-coverage-reporter/target
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ../../codacy-coverage-reporter/target/codacy-coverage-reporter-assembly-1.0.5.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml
  
notifications:
  email:
    recipients:
      - walkersneps@gmail.com
    on_success: change
    on_failure: change
