language:
  java

jdk:
  - oraclejdk8
  - oraclejdk7
  
install:
  - git clone https://github.com/codacy/codacy-coverage-reporter.git
  - sbt assembly
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ../codacy-coverage-reporter/target/codacy-coverage-reporter-assembly-1.0.4.jar com.codacy.CodacyCoverageReporter -l Java -r ./SnepsUtils/target/site/jacoco/jacoco.xml
  
notifications:
  email:
    recipients:
      - walkersneps@gmail.com
    on_success: change
    on_failure: change
