language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    recipients:
      - walkersneps@gmail.com
    on_success: change
    on_failure: change
